### PR TITLE
Lesson planner path

### PR DESCRIPTION
**Pull request by jaredsilver**
For issue #743 

- Updated `lesson_planner` GET route to have path `activity_planner`
- Updated hard-coded links from `lesson_planner` to  `activity_planner`
- Added redirect into routes.rb for `teachers/classrooms/lesson_planner` to the new path with `activity_planner` (including any parameters)

### CODE REVIEW

**Comment by Echelon9** [comment]
Hi @jaredsilver thanks for the PR.
You've probably already noticed, but the continuous integration that's run via Travis is flagging a failure to successfully run `bundle exec rake db:migrate` with this change.
```
ArgumentError: Missing :action key on routes definition, please check your routes.
```

You may also want to take a look at a previous effort PR #1439.

**Comment by jaredsilver** [comment]
Thanks, @Echelon9! I had a spurious `post` sitting beneath the change I made that I somehow didn't notice 😝 I believe it should work from here.

On another note, why do all of the Travis builds say they're failing even if when they pass?

**Comment by Echelon9** [comment]
There's known failing tests on the `develop` branch at present. Have been working though to get the baseline green. i.e. at present:
```
783 examples, 73 failures, 19 pending
```

**Comment by jaredsilver** [comment]
Closing in favor of #2086

**Pull request closed without merging**
