### PR TITLE
Transitioning relevant lib/* to app/lib

### PR DESCRIPTION
**Pull request by happythenewsad**
## WHAT
Moves `lib/` to `app/lib` and makes necessary path adjustments for this change.

## WHY
@brendanshean 's May 13 eng. meeting discussion 
here's a good [post](https://medium.com/extreme-programming/what-goes-in-rails-lib-92c74dfd955e) for reference

Also, from the zeitwerk author: [rails/rails#37835 (comment)](https://github.com/rails/rails/issues/37835#issuecomment-757367812)
and another relevant comment: [rails/rails#13142 (comment)](https://github.com/rails/rails/issues/13142#issuecomment-275492070)
### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
none

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  yes
Have you deployed to Staging? | not yet
Self-Review: Have you done an initial self-review of the code below on Github? | yes
Design Review: If applicable, have you compared the coded design to the mockups? | (N/A

### CODE REVIEW

**Comment by brendanshean** [comment]
@happythenewsad Maybe for context in the PR description, here's a good [post](https://medium.com/extreme-programming/what-goes-in-rails-lib-92c74dfd955e) for reference, specifically, after the **UPDATE** section.

Also, from the zeitwerk author:  https://github.com/rails/rails/issues/37835#issuecomment-757367812
and another relevant comment:  https://github.com/rails/rails/issues/13142#issuecomment-275492070

**Comment by brendanshean** [comment]
I think we should still keep `lib/tasks` in the repo for rake tasks.

**Comment by brendanshean** [comment]
I'd also be curious to hear @dandrabik thoughts on this.

**Comment by happythenewsad** [comment]
I'm converting this to a draft, because it needs more work. The unit tests are passing but manual testing on staging exposes some uncaught exceptions.

**Comment by brendanshean** [comment]
Let me know if there's anything I can help with @happythenewsad .  I really appreciate you undertaking this.

**Comment by happythenewsad** [comment]
> Let me know if there's anything I can help with @happythenewsad . I really appreciate you undertaking this.

I'm working on sprint work the rest of the day. When one of us grabs this work, let's ping the other so we don't duplicate work. If it's not done by end of sprint I will add it to the backlog.

**Comment by dandrabik** [comment]
> I'd also be curious to hear @dandrabik thoughts on this.

I'm not opposed to moving items out of `lib`. It might be worth discussing what the goals of this move would be (since I wasn't there for the meeting). We are autoloading `lib`, so it could stay there.

I'm assuming some of the goals are to make it clear where to put new files (and to stay within current Rails conventions). We already have a few non-standard `app` folders in our project, such as `app/services`, `app/queries`, etc. and we put some non-`ActiveRecord` classes in `app/models`. If we are going to move files, it might make sense to first define where files should go, and then move each file to the appropriate place. This might be more of a reorganization project, than copying over a folder.

Also, as context, like most of those PR comments and that blog post, I typically put code that has no business logic in the `lib` folder, e.g. third-party API wrappers, utility classes that don't reference models, etc. I would have put many of the files that live in `lib` now somewhere else.

**Comment by brendanshean** [comment]
@dandrabik I think that all sounds reasonable to me.

**Comment by brendanshean** [comment]
@happythenewsad I'm going to proceed on this today.

**Comment by happythenewsad** [comment]
Brendan is continuing this work in a separate PR.

**Comment by brendanshean** [comment]
New PR is here: https://github.com/empirical-org/Empirical-Core/pull/7678

**Pull request closed without merging**
