### PR TITLE
add dropdown for sessions

### PR DESCRIPTION
**Pull request by emilia-friedberg**
## WHAT
Add dropdown to make it possible for teachers and students to select sessions to view from their reports pages, rather than only the highest-scoring one. 

## WHY
See explanation in this card: https://www.notion.so/quill/Version-1-5-Part-C-Implement-the-Ability-for-Teachers-Students-to-View-an-Activity-Analysis-Repo-9456f2a582b44bc48943b541575889e7?pvs=4

### Screenshots
Screenshot 2024-04-26 at 10 12 04 AM
Screenshot 2024-04-26 at 10 14 23 AM

### Notion Card Links
https://www.notion.so/quill/Version-1-5-Part-C-Implement-the-Ability-for-Teachers-Students-to-View-an-Activity-Analysis-Repo-9456f2a582b44bc48943b541575889e7?pvs=4

### What have you done to QA this feature?
Tested both the teacher and student report page, with multiple sessions and only one, and in the case of students with "show exact score" both on and off, at various screen sizes.

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  YES
Have you deployed to Staging? | YES
Self-Review: Have you done an initial self-review of the code below on Github? | YES

### CODE REVIEW

**Review by brendanshean — COMMENTED** [review]
I do wonder about the naming of 'session[s]' vs 'activity session[s]'.  Since our codebase has an existing session controller managing a different object, this feels potentially confusing.  Also, session in general is a vague term so I think having activity named explicitly helps with readability.  I also think it's important to try to use the same terms for frontend and backend objects.

I would be curious what others think of this.

**Comment by emilia-friedberg** [comment]
> I do wonder about the naming of 'session[s]' vs 'activity session[s]'. Since our codebase has an existing session controller managing a different object, this feels potentially confusing. Also, session in general is a vague term so I think having activity named explicitly helps with readability. I also think it's important to try to use the same terms for frontend and backend objects.
> 
> I would be curious what others think of this.

@brendanshean this concern makes sense to me. I'll get to work on this renaming.

**Review by brendanshean — APPROVED** [review]
Nice work on this!

**Review by eadams17 — APPROVED** [review]
this looks great-- thanks for putting all of this together!

**Pull request merged**
