### PR TITLE
Bug/broken tests

### PR DESCRIPTION
**Pull request by RyanNovas**
- fixes some tests that broke due to faulty code or switching proficiency levels
- skips frontend tests that were broken due to our switching to React-on-Rails

### CODE REVIEW

**Comment by Echelon9** [comment]
Sounds reasonable given how long running some of the failing tests have been. Down to:
```
771 examples, 43 failures, 34 pending
```

**Comment by RyanNovas** [comment]
@Echelon9, I had it down to zero on my machine -- it seems that Travis has much more trouble with the front end tests. We'll probably have to skip all front-end tests pending us finding a framework that plays more nicely with React.

**Comment by Echelon9** [comment]
Awesome. I remember noting some of the tests were also non-deterministic on Travis between runs, but cleared fine locally.

**Comment by jhack32** [comment]
@RyanNovas Could use Jest for your front end testing with React.

https://facebook.github.io/react/docs/test-utils.html

**Pull request merged**
