### PR TITLE
Oauth fix marcello

### PR DESCRIPTION
**Pull request by kriskelly**
@marcellosachs This looks good, except for 2 things:

- The "custom:" string prefix is apparently necessary for Firebase, so that should get added back.
- Would you mind adding a test for this UID change?

### CODE REVIEW

**Comment by marcellosachs** [comment]
@kriskelly ok modified the code accordingly. How does it look?

**Comment by kriskelly** [comment]
@marcellosachs The other thing that occurred to me, it's not clear whether the uid should be just "custom:" for an anonymous user. Maybe "custom:anonymous"?

**Comment by marcellosachs** [comment]
@kriskelly 'anonymous' seems like a good way to go.

**Comment by kriskelly** [comment]
@marcellosachs Could you add a test for the 'anonymous' part as well? Thx

**Pull request merged**
