### PR TITLE
Use poltergeist/PhantomJS for headless testing

### PR DESCRIPTION
**Pull request by bobmazanec**
Use headless testing to speed up `js: true` examples so external library loads (#614) seem less significant

Got these successful builds as I refined things:

Build # | Total<br>time | `rake spec` time<br>(553 examples)
----- | ---------- | ---------
[61](https://travis-ci.org/bobmazanec/Empirical-Core/builds/58994818) | 4:21 | 1:14
[63](https://travis-ci.org/bobmazanec/Empirical-Core/builds/58995548) | 4:20 | 1:19
[64](https://travis-ci.org/bobmazanec/Empirical-Core/builds/58999349) | 4:14 | 1:21
[65](https://travis-ci.org/bobmazanec/Empirical-Core/builds/58999479) | 3:58 | 1:10
[66](https://travis-ci.org/bobmazanec/Empirical-Core/builds/58999596) | 5:24 | 1:35
[67](https://travis-ci.org/bobmazanec/Empirical-Core/builds/58999638) | 4:14 | 1:11
[68](https://travis-ci.org/bobmazanec/Empirical-Core/builds/58999944) | 6:51 | 1:36
compare to<br>#[1031](https://travis-ci.org/empirical-org/Empirical-Core/builds/58521254)<br>(45bc80e &mdash; on which<br>this branch is based) | 8:46 | 3:37<br>(554 examples)

### CODE REVIEW

**Comment by bobmazanec** [comment]
I clearly see this repo is configured to set/supply `FOG_DIRECTORY` and `PROGRESS_REPORT_FOG_DIRECTORY` env vars, but the [failing build](https://travis-ci.org/empirical-org/Empirical-Core) doesn't show them getting set!?!

**Comment by bobmazanec** [comment]
Rebased onto 3707f0f (expose the required env vars in `.travis.yml`) to make the Travis build succeed.

**Comment by marcellosachs** [comment]
@bobmazanec thanks bob!!

**Comment by marcellosachs** [comment]
@bobmazanec , I'm getting an error when running specs  - 
`Cliver::Dependency::NotFound: Could not find an executable ["phantomjs"] on your path.`
Do I have to install phantom js (http://phantomjs.org/download.html) on my computer? Is there any other configuration involved? Thanks! - marcello

**Comment by bobmazanec** [comment]
Embarrassed apologies &mdash; I didn't even think about documenting poltergeist's [dependence on PhantomJS](https://github.com/teampoltergeist/poltergeist#installing-phantomjs) :embarrassed:

I'll add it to [README](https://github.com/empirical-org/Empirical-Core/blob/develop/README.md)!

**Pull request merged**
