### PR TITLE
evidence/addressable-version-bump

### PR DESCRIPTION
**Pull request by anathomical**
## WHAT
Bump Addressable version in Evidence per Dependabot
## WHY
To stay up to date on our dependencies
## HOW
Update minimum `addressable` version in Gemfile

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  No tests for dependencies
Have you deployed to Staging? | Deploying now
Self-Review: Have you done an initial self-review of the code below on Github? | Yes
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | N/A

### CODE REVIEW

**Review by happythenewsad — APPROVED** [review]
any reason not to specify 
`gem 'addressable', '~> 2.8.0'`

in `Gemfile`?

**Comment by anathomical** [comment]
> any reason not to specify `gem 'addressable', '~> 2.8.0'`
> 
> in `Gemfile`?

I didn't specify it there because `addressable` is not a direct dependency (we don't use it in our code), but a sub-dependency (of `webmock` and `signet`).  So it didn't feel appropriate to add it to our Gemfile.  I could be convinced to do otherwise, though?

**Comment by happythenewsad** [comment]
> > any reason not to specify `gem 'addressable', '~> 2.8.0'`
> > in `Gemfile`?
> 
> I didn't specify it there because `addressable` is not a direct dependency (we don't use it in our code), but a sub-dependency (of `webmock` and `signet`). So it didn't feel appropriate to add it to our Gemfile. I could be convinced to do otherwise, though?

I asked because it's currently a direct dependency in the LMS Gemfile, but not the Evidence Gemfile: https://github.com/empirical-org/Empirical-Core/blob/develop/services/QuillLMS/Gemfile#L85

I just ran LMS specs after removing that line, and they pass. How about removing the direct dependency while you're at it?

**Comment by anathomical** [comment]
> > > any reason not to specify `gem 'addressable', '~> 2.8.0'`
> > > in `Gemfile`?
> > 
> > 
> > I didn't specify it there because `addressable` is not a direct dependency (we don't use it in our code), but a sub-dependency (of `webmock` and `signet`). So it didn't feel appropriate to add it to our Gemfile. I could be convinced to do otherwise, though?
> 
> I asked because it's currently a direct dependency in the LMS Gemfile, but not the Evidence Gemfile: https://github.com/empirical-org/Empirical-Core/blob/develop/services/QuillLMS/Gemfile#L85
> 
> I just ran LMS specs after removing that line, and they pass. How about removing the direct dependency while you're at it?

Specs may pass, but the `Addressable` library is used in the `Activity` model in the base LMS application.  It is therefor a real dependency of the LMS.  It is also a sub-dependency, so it gets installed whether we declare it directly or not, but it's good manners to declare code you actually use directly as a direct dependency, I think.

**Review by cissyxyu — APPROVED** [review]

**Comment by happythenewsad** [comment]
> > > > any reason not to specify `gem 'addressable', '~> 2.8.0'`
> > > > in `Gemfile`?
> > > 
> > > 
> > > I didn't specify it there because `addressable` is not a direct dependency (we don't use it in our code), but a sub-dependency (of `webmock` and `signet`). So it didn't feel appropriate to add it to our Gemfile. I could be convinced to do otherwise, though?
> > 
> > 
> > I asked because it's currently a direct dependency in the LMS Gemfile, but not the Evidence Gemfile: https://github.com/empirical-org/Empirical-Core/blob/develop/services/QuillLMS/Gemfile#L85
> > I just ran LMS specs after removing that line, and they pass. How about removing the direct dependency while you're at it?
> 
> Specs may pass, but the `Addressable` library is used in the `Activity` model in the base LMS application. It is therefor a real dependency of the LMS. It is also a sub-dependency, so it gets installed whether we declare it directly or not, but it's good manners to declare code you actually use directly as a direct dependency, I think.

Thanks for the explanation - carry on!

**Pull request merged**
