### PR TITLE
Sort students by last name

### LINKED ISSUE #584: Arrange students by last name
Can we set it up so that students are arranged by the first character of their last name? Since we don't ask students to input both a first and last name, some may not have both. @bobmazanec

### PR DESCRIPTION
**Pull request by bobmazanec**
Fixes #584 

Sort students by last name on Teacher pages:
- Classroom Manager | Invite Students
- Scorebook
- Activity Planner | Create a Unit (phase 2 &mdash; assigning the activity)

Along the way...
- add new feature specs & supporting 'page' objects
- convert 3 ERB files to SLIM

### CODE REVIEW

**Comment by bobmazanec** [comment]
Yup &mdash; that's my new example:

```
  1) Teacher Activity Planner - Create a Unit given a selectable Activity and a classroom with students when signed in as the Teacher shows the students, sorted by last name
     Failure/Error: expect(lesson_planner_page.students)
       
       expected: ["Christopher Brown", "Chris", "Christine", "Christopher", "Alex Smith"]
            got: []
       
       (compared using ==)
     # ./spec/features/teacher/activity_planner/create_unit_spec.rb:24:in `block (5 levels) in <top (required)>'

[...]

402 examples, 1 failure, 7 pending

Failed examples:

rspec ./spec/features/teacher/activity_planner/create_unit_spec.rb:18 # Teacher Activity Planner - Create a Unit given a selectable Activity and a classroom with students when signed in as the Teacher shows the students, sorted by last name

Randomized with seed 27647
```

Interestingly, it worked on...
- [my repo](https://travis-ci.org/bobmazanec/Empirical-Core/builds/53518970) &mdash; seed 55550
- my MacBook &mdash; seed 27647

More when I know it; ideas welcome in the meantime...

**Comment by RyanNovas** [comment]
@marcellosachs could you check this and merge if all looks good?

**Comment by bobmazanec** [comment]
@RyanNovas & @marcellosachs: thanks

You may have seen I've merged in a small build change so far, but I've left this PR open in case you had any feedback and/or requests.

**Comment by bobmazanec** [comment]
Re-organized & simplified the commits
Rebased onto `develop` 7e2c49d

**Pull request merged**
