### PR TITLE
Reflect Cissy’s promotion on team page.

### PR DESCRIPTION
**Pull request by dandrabik**
## WHAT
Update Cissy's title to 'Software Developer'
## WHY
It's her new title.
## HOW
Copy change

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  NO, copy change
Have you deployed to Staging? | NO - tiny change
Self-Review: Have you done an initial self-review of the code below on Github? | Yes
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | N/A

### CODE REVIEW

**Review by emilia-friedberg — APPROVED** [review]
Yay Cissy!

**Review by happythenewsad — APPROVED** [review]

**Review by anathomical — APPROVED** [review]
HUZZAH!

**Comment by anathomical** [comment]
Should we update Emilia at this point, too?

**Review by brendanshean — APPROVED** [review]
🎉  Yeah Cissy!

**Review by eadams17 — APPROVED** [review]

**Review by cissyxyu — APPROVED** [review]

**Pull request merged**
