### PR TITLE
hides teacher resources and discover from student view

### PR DESCRIPTION
**Pull request by NColey**
This pull request intends to fix Issue #1036. I edited the views/application/_sub_header.html.erb file to wrap the discover and teacher resources links in the following if statement: `if !current_user || current_user.role != "student"` so that users who are logged in as a student will not see the discover and teacher resources links but users logged in as teachers or admin, and users that are not logged in will be able to see them. This was added on line 18 under `<ul class="home-navbar-list">`.

### CODE REVIEW

**Comment by RyanNovas** [comment]
Thanks @NColey, you've helped a nonprofit that provides free writing activities to thousands of children a day!

We'll review this soon and let you know if it gets merged in.

If you ever have any questions about our codebase or Quill in general, our Slack, https://community.quill.org/join-slack/, is the best place to ask them.

By the way, how did you find us?

Best,

Ryan

**Comment by NColey** [comment]
Thank you! I found out about Quill through a first time open source contributor meetup I went to on Sunday, hosted by Thoughtbot and the Hacker Hours meetup group. I'm currently a student at the Flatiron School, a coding bootcamp, and had never contributed to anything open source before so it was really exciting and I loved looking through Quill's codebase, it was a great learning experience!

**Comment by RyanNovas** [comment]
Awesome, I'll definitely check out the next meetup. Also, I just graduated from Flatiron in October -- I'm excited to see that the next cohort is already making open source contributions!

**Comment by NColey** [comment]
That would be fantastic, if you're interested in checking out on of the meetups they are hosted by [Hacker Hours](http://www.meetup.com/hackerhours/), I'm not sure how frequently the open source contributor meetups are hosted but I'm sure they would love to have you there!

**Pull request merged**
