### PR TITLE
compress csvs before emailing them

### PR DESCRIPTION
**Pull request by emilia-friedberg**
## WHAT
Compress feedback session CSVs before mailing them.

## WHY
This is another attempt to fix the bugs mentioned [in this PR](https://github.com/empirical-org/Empirical-Core/pull/10603). It turns out [Sendgrid has a hard 30mb limit](https://docs.sendgrid.com/api-reference/mail-send/limitations#:~:text=The%20total%20size%20of%20your,must%20no%20more%20than%201000.), and our CSVs are definitely exceeding that - I tested locally and one 7k-ish response file was 19.2mb, and the example queries Hannah sent me were closer to 22k lines. When I ran this locally, that 19.2mb file compressed to 2mb, so I'm optimistic this will work as a solution at least for the time being.

## HOW
Just compress the file before sending it using ActiveRecord's gzip.

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
https://www.notion.so/quill/Email-Me-CSV-Data-button-not-working-on-View-Sessions-page-86ad7b0514a64c32beb37cee28f4ca41

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? | YES
Have you deployed to Staging? | no - tiny change, tested locally
Self-Review: Have you done an initial self-review of the code below on Github? | YES
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | N/A

### CODE REVIEW

**Review by anathomical — APPROVED** [review]
Seems like a totally reasonable solution that will hopefully work for our use cases.

**Review by happythenewsad — CHANGES_REQUESTED** [review]
`FEEDBACK_SESSIONS_CSV_FILENAME`'s value is `feedback_sessions.csv`, so we should probably change that to `feedback_sessions.zip`.
 
 Also, I want to note that some orgs don't let zipfiles through. I don't know what %, however.

**Comment by emilia-friedberg** [comment]
> `FEEDBACK_SESSIONS_CSV_FILENAME`'s value is `feedback_sessions.csv`, so we should probably change that to `feedback_sessions.zip`.
> 
> Also, I want to note that some orgs don't let zipfiles through. I don't know what %, however.

@happythenewsad changed file name! This emails are only internal (they only go to quill.org email addresses), and we aren't currently blocking zipfiles.

**Review by happythenewsad — APPROVED** [review]
👍

**Pull request merged**
