### PR TITLE
Rake task to convert unit template information to markdown

### PR DESCRIPTION
**Pull request by jaredsilver**
This fixes part of #3182.

### CODE REVIEW

**Comment by ddmck** [comment]
@jaredsilver lets also grab the author data and convert to markdown.

**Comment by jaredsilver** [comment]
Looking at this again, I actually don't see the author data anywhere here. I think so long as we maintain the author_id on UnitTemplate (which we don't change here or in #3187), I don't think we need to worry.

One thing is that in #3187 I removed a couple Jest tests related to the author data displaying, so I'll add that back in.

But this one should be ready to go.

:shipit:

**Comment by jaredsilver** [comment]
Actually, I spoke too soon. It was grabbing the author data from the authors table, but it looks like we were trying to deprecate this at some point and convert everything to the UnitTemplate.activity_info column. I'll just port over the author info from the authors table statically I suppose.

**Comment by jaredsilver** [comment]
Welp, I've changed my mind once again. It turns out that there are actually no author descriptions currently in the production database, so we can safely ignore the entire author aspect of these two PRs altogether.

This is good to merge, deploy, and run. :shipit:

**Pull request merged**
