### PR TITLE
Teacher sign up & home page feature specs

### PR DESCRIPTION
**Pull request by bobmazanec**
Add (minimal) initial [`feature`](http://www.relishapp.com/rspec/rspec-rails/docs/feature-specs/feature-spec) specs, along with supporting infrastructure/framework to facilitate and  encourage more.

This branch is based on and, thus, includes, PRs...
* [#534 - Run specs under spring to reduce file load times](https://github.com/empirical-org/Empirical-Core/pull/534)
* [#523 - Speed up specs w/ DbCleaner :transaction strategy](https://github.com/empirical-org/Empirical-Core/pull/523)
* [#522 - Empty db before running specs](https://github.com/empirical-org/Empirical-Core/pull/522)
* [#521 - Add spec/rails_helper.rb](https://github.com/empirical-org/Empirical-Core/pull/521)
* [#548 - Fix spurious serializer spec test failures](https://github.com/empirical-org/Empirical-Core/pull/548)

### CODE REVIEW

**Comment by bobmazanec** [comment]
1) Teacher signup allows class creation
       Failure/Error: let(:sign_up_page) { SignUpPage.visit }
       Selenium::WebDriver::Error::WebDriverError:
         unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)
       [...]

1 of the 3 feature specs timed out, but the other 2 ran; maybe this was the first?
                                                                                
    2) ClassificationSerializer has expected attributes classification object should have these keys
       Failure/Error: expect(classification_json.keys).to eq(expected)
         
         expected: ["uid", "id", "name", "key", "form_url", "module_url", "created_at", "updated_at", "image_class", "scorebook_icon_class", "alias"]
              got: ["uid", "id", "name", "key", "form_url", "module_url", "created_at", "updated_at", "image_class", "alias", "scorebook_icon_class"]

Looks like an ordering problem -- needs [`contains_exactly`](http://www.rubydoc.info/github/rspec/rspec-expectations/RSpec/Matchers#contain_exactly-instance_method) or [`match_array`](http://www.rubydoc.info/github/rspec/rspec-expectations/RSpec/Matchers#match_array-instance_method)?

**Comment by bobmazanec** [comment]
I've started on fixing the serializer specs; PR 'soon'...

**Comment by bobmazanec** [comment]
PR #548

**Comment by petergault** [comment]
Thanks for the PR! The core devs are behind with other projects right now,
and we will be meeting to review all of the PRs next Monday the 23rd. I'll
try to get to this as soon as we can.

On Fri, Feb 13, 2015 at 5:38 PM, Bob Mazanec <notifications@github.com>
wrote:

> PR #548 <https://github.com/empirical-org/Empirical-Core/pull/548>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/pull/547#issuecomment-74339781>
> .
>



-- 
Peter Gault
Quill Co-Founder and Product Director
http://quill.org

Learn more about Quill: http://youtu.be/BA6jaeberMg

**Comment by bobmazanec** [comment]
Thanks.

As you and the team are changing user workflow(s), these first few feature specs and the 'framework' behind/around them might give the team a start on doing some BDD/TDD while working through the changes.

**Comment by bobmazanec** [comment]
Then again, not ready for 'prime time' yet...

**Pull request closed without merging**
