### PR TITLE
add airbyte convenience script

### PR DESCRIPTION
**Pull request by happythenewsad**
## WHAT
Convenience script for airbyte devops 

## WHY
Current script is not versioned in the mono repo. 

This way, all users will get updates to the script, when required. 
Also, this new script manages tunnels on different ports, so that you can run more than one tunnel in parallel.

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
https://www.notion.so/quill/Product-Board-30f97e4eb01246dbb8264253fb385073?p=8fbc93a449fd44a4bb3a7b40a74f93dc&pm=s

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  tested manually
Have you deployed to Staging? | n/a
Self-Review: Have you done an initial self-review of the code below on Github? | yes
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | (N/A or Yes)

### CODE REVIEW

**Review by anathomical — APPROVED** [review]
Nice!  Having this in version control is nice.  I won't have to keep trying to remember the tunnel commands.

**Review by dandrabik — CHANGES_REQUESTED** [review]
This is a great start. I'd like to make this script interactive to cut down on what a developer needs to know to use it, so this is my proposed UI:
```
# move script inside the LMS, either in script/ or bin/dev/
# developer runs generic script command, e.g. script/airbyte
What would you like to do?
1. Open the Airbyte UI
2. ssh into a Airbyte server

Enter a number: 
# developer enters a number

Which group of tables would you like to access?
1. concept_results
2. classrooms, classroom_units, provider_classroom_users, students_classrooms, unit_activities
3. All other tables

Enter a number: 
# developer enters a number

# Script prints out the command it is running, link to the more info notion doc, then run the command
# If it is accessing the Airbyte UI, open the url in a browser.

**Comment by happythenewsad** [comment]
> This is a great start. I'd like to make this script interactive to cut down on what a developer needs to know to use it, so this is my proposed UI:
> 
> ```
> # move script inside the LMS, either in script/ or bin/dev/
> # developer runs generic script command, e.g. script/airbyte
> What would you like to do?
> 1. Open the Airbyte UI
> 2. ssh into a Airbyte server
> 
> Enter a number: 
> # developer enters a number
> 
> Which group of tables would you like to access?
> 1. concept_results
> 2. classrooms, classroom_units, provider_classroom_users, students_classrooms, unit_activities
> 3. All other tables
> 
> Enter a number: 
> # developer enters a number
> 
> # Script prints out the command it is running, link to the more info notion doc, then run the command
> # If it is accessing the Airbyte UI, open the url in a browser.
> ```

In response to your feedback I have:
- added command printing
- auto-open URL in browser (great idea)
- moved the script into LMS (good for convenience, not so good for separation of concerns)

I recommend not doing the interactive UX, since it does not add any information that the `usage` doesn't already have:

```
Usage: airbyte ssh|tunnel INSTANCE 

INSTANCE	 | PORT | HOSTED TABLES
airbyte2	 | 8001 | concept_results
airbyte-pink	 | 8002 | classrooms classroom_units provider_classroom_users  students_classrooms unit_activities
airbyte-0-43-0	 | 8003 | all_other_tables
```


... and having to go through the sequence of interactive prompts every time will get tiresome (like going through the Evidence student playthrough preamble, before we added the `skipToPrompts` flag).

**Comment by dandrabik** [comment]
> > This is a great start. I'd like to make this script interactive to cut down on what a developer needs to know to use it, so this is my proposed UI:
> > ```
> > # move script inside the LMS, either in script/ or bin/dev/
> > # developer runs generic script command, e.g. script/airbyte
> > What would you like to do?
> > 1. Open the Airbyte UI
> > 2. ssh into a Airbyte server
> > 
> > Enter a number: 
> > # developer enters a number
> > 
> > Which group of tables would you like to access?
> > 1. concept_results
> > 2. classrooms, classroom_units, provider_classroom_users, students_classrooms, unit_activities
> > 3. All other tables
> > 
> > Enter a number: 
> > # developer enters a number
> > 
> > # Script prints out the command it is running, link to the more info notion doc, then run the command
> > # If it is accessing the Airbyte UI, open the url in a browser.
> > ```
> 
> In response to your feedback I have:
> 
> * added command printing
> * auto-open URL in browser (great idea)
> * moved the script into LMS (good for convenience, not so good for separation of concerns)
> 
> I recommend not doing the interactive UX, since it does not add any information that the `usage` doesn't already have:
> 
> ```
> Usage: airbyte ssh|tunnel INSTANCE 
> 
> INSTANCE	 | PORT | HOSTED TABLES
> airbyte2	 | 8001 | concept_results
> airbyte-pink	 | 8002 | classrooms classroom_units provider_classroom_users  students_classrooms unit_activities
> airbyte-0-43-0	 | 8003 | all_other_tables
> ```
> 
> ... and having to go through the sequence of interactive prompts every time will get tiresome (like going through the Evidence student playthrough preamble, before we added the `skipToPrompts` flag).

So, it's fair that given your amount of usage you'd benefit from having the direct commands. I think that most other people, however, will access these commands relatively infrequently, so the interactive UI would be helpful. You can refactor this code so that `airbyte` without args runs the interactive shell, and `airbyte` with args does the direct command if you like. Either way, I'd still appreciate having the interactive shell. This is something that should only take 30 minutes or so to refactor.

**Comment by happythenewsad** [comment]
OK, I've made the script interactive. I'll try it out myself and may add the faster non interactive syntax later.

**Review by dandrabik — APPROVED** [review]
This looks good, thanks for making the requested changes. I just used it to login to the UIs. Super easy.

**Pull request merged**
