### PR TITLE
add grades 1 + 2 to Classroom::GRADES

### PR DESCRIPTION
**Pull request by avifoxi**
Hi - new to the project, referred by Code Montage. 

I made small change to Classroom::GRADES, adding 1 + 2 as @RyanNovas requested in the issues queue --

didn't test this as it's not a new feature --- 
in the tests that exist, I had 248 examples, 7 failures, 5 pending before and after the change--- so this doesn't seem to break anything new!

please let me know if I'm missing anything for standard workflow, I'd like to contribute some more.
Thnx!
AFR

### CODE REVIEW

**Comment by Ryan-Quill** [comment]
Hi @avifoxi, welcome to Quill, we're excited to have you helping!

@marcellosachs can review your pull request and will merge it if all looks good.

**Comment by marcellosachs** [comment]
Hi @avifoxi , this looks good! Thanks for your help!

**Comment by avifoxi** [comment]
Thanks!
will keep hunting and hope to submit again soon -
best-
Avi

On Tue, Jan 13, 2015 at 4:32 PM, marcellosachs <notifications@github.com>
wrote:

> Merged #481 <https://github.com/empirical-org/Empirical-Core/pull/481>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/pull/481#event-218383388>
> .
>



-- 
Avi Fox-Rosen
Musician + Web Developer
avifoxi.github.io
github.com/avifoxi

**Comment by marcellosachs** [comment]
@avifoxi awesome!
best,
marcello

**Comment by RyanNovas** [comment]
@avifoxi, we could always use more help. If you're interested #463, #438, #16, and #482 could be worth looking into.

We also have a community page you should sign up for (http://community.quill.org) and a chat room you can access here: http://community.quill.org/chat/

**Pull request merged**
