### PR TITLE
Adds rake task to titleize schools data points

### LINKED ISSUE #3788: Create a rake task to titleize all schools in the database
Quill has a database of almost every school in the United States. Unfortunately, our data sets were inconsistent, so some of the formatting is different for different schools. In particular, the names of many schools are all capitalized, when they should be titleized.

Please write a rake task that will iterate through every school in the schools table and titelize the name, address, and other relevant data points of the school.

### PR DESCRIPTION
**Pull request by kartik-25**
Fixes #3788

**Changes proposed in this pull request:**
- Adds Rake tasks for titleizing schools data points

**Reviewer:** @jaredsilver  @petergault

### CODE REVIEW

**Comment by jaredsilver** [comment]
Thanks so much for doing this, @kartik-25! Can you foresee any problems that might arise if the school in question doesn't have all of this information? For example, what would happen if `school.city` is `NULL`?

**Comment by kartik-25** [comment]
@jaredsilver I tested it on my local and no issue arose. I think titleize must be handling such cases internally.

**Comment by jaredsilver** [comment]
Run this in phppgadmin, and then try running the Rake task again. Does it still work?

```
INSERT INTO "public"."schools"("id","nces_id","lea_id","leanm","name","phone","mail_street","mail_city","mail_state","mail_zipcode","street","city","state","zipcode","nces_type_code","nces_status_code","magnet","charter","ethnic_group","longitude","latitude","ulocal","fte_classroom_teacher","lower_grade","upper_grade","school_level","free_lunches","total_students","created_at","updated_at","clever_id","ppin")
VALUES
(128456,NULL,NULL,NULL,E'WISCONSIN ACADEMY',NULL,E'N2355 DU BORG RD',E'COLUMBUS',E'WI',E'53925',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,-89.050121,43.36613,41,9,9,12,2,NULL,121,E'2017-10-04 04:52:30.946792',E'2017-10-04 04:52:30.946792',NULL,E'1516293');
```

**Comment by kartik-25** [comment]
@jaredsilver fixed that issue. Please, have a look.

**Comment by kartik-25** [comment]
😄

**Pull request merged**
