### PR TITLE
Migrate 16.2.0

### PR DESCRIPTION
**Pull request by pandeykartikey**
Addresses issue #3860

**Changes proposed in this pull request:**
- Updates packages in package.json
- Changes React.createClass to createReactClass 
- Changes React.Proptypes to Proptypes from prop-types package

**Have the tests been updated?** done

**Reviewer:** @ddmck

### CODE REVIEW

**Comment by kartik-25** [comment]
@ddmck  I am facing problem in resolving the issue with test `app/bundles/HelloWorld/containers/__tests__/TeacherAccount.test.jsx`. Can you help me here?

**Comment by kartik-25** [comment]
@ddmck I am facing problem in resolving the issue with test `app/bundles/HelloWorld/components/lesson_planner/manage_units/__tests__/classroom_activity.test.jsx`. Can you help me here?

**Comment by kartik-25** [comment]
@ddmck  Almost everything is done just need a little bit guidance in resolving the problem with tests of `classroom_activity` & `classroom_page`. Please have look at the current progress and suggest changes, if required.

**Comment by ddmck** [comment]
@kartik-25 I will have someone look at the failing tests tomorrow, this looks great though!

**Comment by pandeykartikey** [comment]
@ddmck only two tests are failing now.

**Comment by pandeykartikey** [comment]
@ddmck I had fixed the tests finally. But after merge the PR broke again :cry:

**Pull request closed without merging**
