### PR TITLE
Cms/update ruby version

### PR DESCRIPTION
**Pull request by anathomical**
## WHAT
Bump the version of `Ruby` to 2.6.8 for the CMS since the new AWS environment is running that version.  Also bump the version of `Bundler` to 2.2 to catch up with the version used in the AWS environment.
## WHY
We can't upgrade to using the newest version of the environment if we don't bring our tools into adjacent versions.
## HOW
Just update local Ruby version for CMS and follow on with a Bundler update and new `bundle install` run.

### Notion Card Links
https://www.notion.so/quill/Upgrade-deprecated-CMS-platform-version-bfc10fd51488403a847830409e829c0c

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  No tests on Gemfile configs
Have you deployed to Staging? | Yes
Self-Review: Have you done an initial self-review of the code below on Github? | Yes
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | N/A

### CODE REVIEW

**Comment by happythenewsad** [comment]
@anathomical CircleCI is failing hard on this PR. Should we hold off reviewing until it passes?

**Comment by anathomical** [comment]
@happythenewsad Good catch.  I figured out what CI config tweaks were needed to get it to pass.

**Review by happythenewsad — APPROVED** [review]

**Review by dandrabik — APPROVED** [review]
:+1: Looks good to me. 

Note, it might be worth adding to the Readme (and posting in Slack). That'll you'll likely need to run  a few commands to make this work locally (this is what I hit), e.g.
```
rbenv install
# you may need to fetch new ruby versions (it'll give you an error if it's not found)
#  git -C /Users/danieldrabik/.rbenv/plugins/ruby-build pull
gem install bundler:2.2.27
bundle install
```

**Comment by anathomical** [comment]
This isn't necessary after the CMS was migrated to Heroku.

**Pull request closed without merging**
