### PR TITLE
Kill off some old routes 🚽

### PR DESCRIPTION
**Pull request by jaredsilver**

### CODE REVIEW

**Comment by ddmck** [comment]
@jaredsilver /me is used by the mobile app. /ping is used by some of our downtime monitors.

**Comment by jaredsilver** [comment]
@ddmck Ah, that makes sense. Closing this issue.

**Comment by jaredsilver** [comment]
Oh wait, just kidding -- there are still a couple dead routes in here. Reopening and updating the PR.

**Comment by jaredsilver** [comment]
Okay 👍

**Pull request merged**
