### PR TITLE
Fix #3453: Redirect teacher to the invite students page after creating a new class

### LINKED ISSUE #3453: Strange UX on adding a new classroom
If a teacher already has students associated with one or more classroom, adding a new classroom will redirect them to the scorebook. We should probably redirect them instead to the invite students page for that new classroom.

### PR DESCRIPTION
**Pull request by jaredsilver**

### CODE REVIEW

**Comment by ddmck** [comment]
@jaredsilver For onboarding reasons we want Teachers to assign content before adding students when they sign up. If you can make it so that they are still redirected on sign up based on the presence of Units created by the teacher, I'd be happy to merge this.

The behavior should be:
No students and no units -> to assign activities route.
No students and units. -> to invite students.

**Comment by ddmck** [comment]
@jaredsilver  let's add a spec and then we will merge!

**Comment by jaredsilver** [comment]
Should be good to go now if tests pass 👍

**Comment by jaredsilver** [comment]
I have no idea why tests keep failing on this branch.

`Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)`

We're not touching any dependencies or styles, yet this seems to be the only branch this is happening on... ¯\_(ツ)_/¯

**Pull request merged**
