### PR TITLE
Updated hash syntax to Ruby 1.9 symbol notation

### PR DESCRIPTION
**Pull request by askl56**

### CODE REVIEW

**Comment by ddmck** [comment]
@askl56 Thanks for making this pull request. I'm going to review it and merge it once I get Travis CI passing (this isn't your fault).

How did you come across the repo? 

Unrelated: I did some snooping on you and saw that you went to Gordonstoun, I grew up in Lossiemouth and Elgin so we were almost neighbours!

**Comment by askl56** [comment]
Was asking around for great examples of open source Rails projects in #ruby on Freenode.

Let me know via highlight when travis is fixed. What seems to be the problem?

**Comment by askl56** [comment]
Also yeah went to Gordonstoun, it's a small world!

**Comment by ddmck** [comment]
@askl56 We have some benchmark tests that measure the amount of time a certain query takes to run, and they don't consistently pass on the travis VM's. It'll be merged by the end of the week.

**Pull request merged**
