### PR TITLE
Move relevant files from lib/ to 'app/lib/'

### PR DESCRIPTION
**Pull request by brendanshean**
## WHAT
Moves lib/ to app/lib and makes necessary path adjustments for this change.

## WHY
@brendanshean 's May 13 eng. meeting discussion
here's a good post for reference

Also, from the zeitwerk author: rails/rails#37835 (comment)
and another relevant comment: rails/rails#13142 (comment)

## HOW

More detail in Peter Kong's original PR: https://github.com/empirical-org/Empirical-Core/pull/7649

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
https://www.notion.so/quill/LMS-Move-lib-to-app-lib-85fc6ae5895d41f587c20704328d2497

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  No.
Have you deployed to Staging? |  Not yet - deploying now!
Self-Review: Have you done an initial self-review of the code below on Github? |. YES
Design Review: If applicable, have you compared the coded design to the mockups? | (N/A or Yes). N/A

### CODE REVIEW

**Review by dandrabik — CHANGES_REQUESTED** [review]
Thanks for cleaning this up! A few files that might be better to leave and/or delete (happy to discuss if there are reasons to move/keep):

- `lib/assets/.gitkeep` I think we can just delete this (to avoid another `assets` directory in `app`).
- Everything in `lib/data` seems to be used by migrations or rake tasks (you can confirm by searching by filename). I think we should leave this folder in `lib`.

**Comment by brendanshean** [comment]
@dandrabik Those are sensible suggestions.  I have updated the PR.

**Review by dandrabik — APPROVED** [review]
Thanks for making the changes!

**Review by happythenewsad — APPROVED** [review]

**Comment by brendanshean** [comment]
@happythenewsad @dandrabik I moved AsyncHelper into `spec/support` since it was preventing the build to complete.  (It's only used by one spec in particular).
Screen Shot 2021-05-20 at 2 48 56 PM

**Review by dandrabik — APPROVED** [review]
:+1: LGTM. Thanks for moving this along.

**Pull request merged**
