### PR TITLE
Classroom Student Login Information PDFs

### PR DESCRIPTION
**Pull request by jaredsilver**
Addresses issue #1785

### CODE REVIEW

**Comment by ddmck** [comment]
Ok, this is looking great so far. There were some details we forgot. If a student has a clever_id on their model, or signed_up_with_google is true the print out should tell them which service to log in with, and which email to use with the service

EXAMPLE: 
John Doe
username:  john.doe@quill-rules
default password: Doe

Jane Doe (has google)
email: janedoe@gmail.com
password: Login with Google with the above email address

James Doe (has clever)
email: jamesdoe@clever.com
password: Login with Clever with the above email address

**Comment by ddmck** [comment]
I also made a pull request to your branch which fixes an error.

**Comment by jaredsilver** [comment]
Updated! 😄

**Comment by jaredsilver** [comment]
@ddmck -- just added a basic test to ensure teachers can only download their own classrooms' login data. In general, what is this project's approach to testing?

**Comment by RyanNovas** [comment]
@jaredsilver,  on the backend, we aim for 100% unit and component testing.  We are sorely lacking a front-end testing framework and need to get that sorted out.

**Pull request merged**
